In [1]:
import pandas as pd
import plotly.graph_objects as go
import datetime as dt

In [56]:
pair = 'EUR_USD'
granularity = 'H4'
df = pd.read_pickle(f'../data/{pair}_{granularity}.pkl')
df['sTime'] = [dt.datetime.strftime(i, "s%Y-%m-%d %H:%M") for i in df['time']]

In [57]:
df.head()

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c,sTime
0,2022-07-01 01:00:00+00:00,18405,1.04716,1.04738,1.04472,1.04539,1.04709,1.04731,1.04463,1.04532,1.04724,1.04747,1.04480,1.04546,s2022-07-01 01:00
1,2022-07-01 05:00:00+00:00,30437,1.04538,1.04706,1.04328,1.04590,1.04531,1.04698,1.04320,1.04580,1.04546,1.04714,1.04335,1.04600,s2022-07-01 05:00
2,2022-07-01 09:00:00+00:00,30403,1.04590,1.04742,1.04066,1.04066,1.04580,1.04734,1.04059,1.04059,1.04599,1.04751,1.04073,1.04074,s2022-07-01 09:00
3,2022-07-01 13:00:00+00:00,43098,1.04066,1.04200,1.03655,1.04014,1.04060,1.04193,1.03647,1.04006,1.04073,1.04207,1.03663,1.04021,s2022-07-01 13:00
4,2022-07-01 17:00:00+00:00,12708,1.04010,1.04330,1.03934,1.04265,1.04002,1.04322,1.03926,1.04250,1.04017,1.04339,1.03941,1.04280,s2022-07-01 17:00

In [58]:
df_plot = df.iloc[:100]
df_plot.head()

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c,sTime
0,2022-07-01 01:00:00+00:00,18405,1.04716,1.04738,1.04472,1.04539,1.04709,1.04731,1.04463,1.04532,1.04724,1.04747,1.04480,1.04546,s2022-07-01 01:00
1,2022-07-01 05:00:00+00:00,30437,1.04538,1.04706,1.04328,1.04590,1.04531,1.04698,1.04320,1.04580,1.04546,1.04714,1.04335,1.04600,s2022-07-01 05:00
2,2022-07-01 09:00:00+00:00,30403,1.04590,1.04742,1.04066,1.04066,1.04580,1.04734,1.04059,1.04059,1.04599,1.04751,1.04073,1.04074,s2022-07-01 09:00
3,2022-07-01 13:00:00+00:00,43098,1.04066,1.04200,1.03655,1.04014,1.04060,1.04193,1.03647,1.04006,1.04073,1.04207,1.03663,1.04021,s2022-07-01 13:00
4,2022-07-01 17:00:00+00:00,12708,1.04010,1.04330,1.03934,1.04265,1.04002,1.04322,1.03926,1.04250,1.04017,1.04339,1.03941,1.04280,s2022-07-01 17:00

In [59]:
fig = go.Figure()
fig.add_trace(go.Candlestick
            (x=df_plot['sTime'],
                open=df_plot['mid_o'],
                high=df_plot['mid_h'],
                low=df_plot['mid_l'],
                close=df_plot['mid_c'],
                name='Candlesticks'))

# Note that there are missing data (due to weekends)

In [62]:
fig = go.Figure()
fig.add_trace(go.Candlestick(
                x=df_plot['sTime'],
                open=df_plot['mid_o'],
                high=df_plot['mid_h'],
                low=df_plot['mid_l'],
                close=df_plot['mid_c'],
                name='Candlesticks'),
                )
fig.update_yaxes(
    gridcolor='rgb(15,15,15)',
)

fig.update_xaxes(
    gridcolor='rgb(15,15,15)',
    rangeslider_visible=False,
    nticks = 10,
)
fig.update_layout(
    width=1500,
    height=400,
    margin = dict(l = 10, r = 10, t = 10, b = 10),
    paper_bgcolor='#1f2630',
    plot_bgcolor='#1f2630',
    font = dict(size = 8, color='white'),
)

fig.show()